include /home/barab/.config/brice/kitty.conf
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
shell_integration enabled
notify_on_cmd_finish invisible
map ctrl+c copy_or_interrupt
map ctrl+shift+c send_text all \x03\\
map ctrl+v paste_from_clipboard
map f11 toggle_fullscreen
map ctrl+backspace send_text all \x17
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
confirm_os_window_close 0
background_opacity 0.8
map --allow-fallback=shifted,ascii ctrl+shift+w close_tab
map --allow-fallback=shifted,ascii ctrl+shift+t new_tab
map --allow-fallback=shifted,ascii ctrl+t new_window
map --allow-fallback=shifted,ascii ctrl+w close_window
map ctrl+tab next_window
map ctrl+shift+tab next_tab
