[background]
# Path to the background image
path = "/etc/greetd/regreet.png"
[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Classic"
[appearance]
greeting_msg = "Re"
