[background]
# Path to the background image
path = "/etc/greetd/wallpaper.png"
[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Classic"
[appearance]
# The message that initially displays on startup
greeting_msg = "C'est qui ?"
